version: "3"

dotenv: [".env"] # optional: lets you move config out of bash later

vars:
  SCRIPTS: scripts

tasks:
  default:
    cmds:
      - task -l

  doctor:
    desc: "Check required tools are installed"
    cmds:
      - |
        set -euo pipefail
        need() { command -v "$1" >/dev/null || { echo "Missing: $1"; exit 1; }; }
        need bash
        need git
        need makepkg
        need repo-add
        need mkarchroot
        need makechrootpkg
        echo "OK"

  update:
    desc: "Update PKGBUILDs (feeds/AUR/etc) without building"
    cmds:
      - bash "{{.SCRIPTS}}/update-pkg.sh"

  aur-import:
    desc: "Clone a package from the AUR and add it to the feeds.json file for updates"
    cmds:
      - bash "{{.SCRIPTS}}/aur-imports.sh"

  cleanup:
    desc: "Cleanup repo artifacts / old packages"
    cmds:
      - git clean -fdx
