version: "3"

dotenv: [".env"] # optional: lets you move config out of bash later

vars:
  SCRIPTS: scripts

tasks:
  default:
    cmds:
      - task -l

  doctor:
    desc: "Check required tools are installed"
    cmds:
      - |
        set -euo pipefail
        need() { command -v "$1" >/dev/null || { echo "Missing: $1"; exit 1; }; }
        need bash
        need git
        need makepkg
        need repo-add
        need mkarchroot
        need makechrootpkg
        echo "OK"

  update:
    desc: "Update PKGBUILDs (feeds/AUR/etc) without building"
    cmds:
      - bash "{{.SCRIPTS}}/update-pkg.sh"

  review:
    desc: "Review PKGBUILD changes (diffs / prompts)"
    cmds:
      - bash "{{.SCRIPTS}}/review-pkgbuild.sh"

  build:
    desc: "Build packages (recommended: chroot)"
    deps: [doctor]
    cmds:
      - bash "{{.SCRIPTS}}/build-chroot.sh"

  repo:
    desc: "Update repo database / add built packages"
    deps: [doctor]
    cmds:
      - bash "{{.SCRIPTS}}/repo-mgmt.sh"

  cleanup:
    desc: "Cleanup repo artifacts / old packages"
    cmds:
      - git clean -fdx

  install:
    desc: "Install updates from your repo (be careful; keep this simple)"
    deps: [doctor]
    cmds:
      - bash "{{.SCRIPTS}}/install-updates.sh"

  sync:
    desc: "End-to-end: update → optional review → build → repo → optional install"
    deps: [doctor]
    cmds:
      - task: update
      - task: review
      - task: build
      - task: repo

  sync-no-review:
    desc: "End-to-end without interactive review"
    deps: [doctor]
    cmds:
      - task: update
      - task: build
      - task: repo
