post_install() {
  echo >&2 'Enabling Wayland (ozone) for electron-fiddle...'
  /usr/share/libalpm/scripts/electron-fiddle-wayland-patch
}

post_upgrade() {
  echo >&2 'Enabling Wayland (ozone) for electron-fiddle...'
  /usr/share/libalpm/scripts/electron-fiddle-wayland-patch
}

pre_remove() {
  echo >&2 'Undoing modifications to electron-fiddle...'
  /usr/share/libalpm/scripts/electron-fiddle-wayland-unpatch
}
