post_install() {
  echo >&2 'Enabling Wayland (ozone) for element-desktop...'
  /usr/share/libalpm/scripts/element-desktop-wayland-patch
}

post_upgrade() {
  echo >&2 'Enabling Wayland (ozone) for element-desktop...'
  /usr/share/libalpm/scripts/element-desktop-wayland-patch
}

pre_remove() {
  echo >&2 'Undoing modifications to element-desktop...'
  /usr/share/libalpm/scripts/element-desktop-wayland-unpatch
}
