post_install() {
  echo >&2 'Enabling Wayland (ozone) for signal-desktop...'
  /usr/share/libalpm/scripts/signal-desktop-wayland-patch
}

post_upgrade() {
  echo >&2 'Enabling Wayland (ozone) for signal-desktop...'
  /usr/share/libalpm/scripts/signal-desktop-wayland-patch
}

pre_remove() {
  echo >&2 'Undoing modifications to signal-desktop...'
  /usr/share/libalpm/scripts/signal-desktop-wayland-unpatch
}
