#!/usr/bin/env bash
#MISE description="Build the package in the current directory in a clean chroot"
#MISE depends=["repo:create", "chroot:create"]
#MISE depends_post=["repo:update"]
#MISE dir="{{cwd}}"

source "${PKGBUILDS_ROOT}/.mise/lib/task.sh"
source "${PKGBUILDS_ROOT}/.mise/lib/repo.sh"
source "${PKGBUILDS_ROOT}/.mise/lib/pkg.sh"

task::bootstrap
task::require_env REPO_DIR REPO_DB CHROOT_DIR

pkg::build_dir "$PWD"
