#!/usr/bin/env bash
#MISE description="Build a package in a clean chroot"
#MISE dir="{{cwd}}"

makechrootpkg -r "$CHROOT_DIR" -c -u \
  -d "${REPO_DIR}:${REPO_DIR}" \
  -- --syncdeps --noconfirm --log